select estado.id, estado.regiao, estado.name, count(*)
from worker_migrations
join estado on worker_migrations.estado = estado.id
where ano = 2004
group by estado.id, estado.regiao, estado.name;

sed -i "1s/^/MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GRAU INSTR;SEXO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002\n/" run/2004/MG.txt


echo 'MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GRAU INSTR;SEXO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002' | cat - run/2004/MG.txt > temp && mv temp run/2004/MG.txt

echo 'MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GRAU INSTR;SEXO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002' | cat - run/2004/RJ.txt > temp && mv temp run/2004/RJ.txt

echo 'MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GRAU INSTR;SEXO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002' | cat - run/2004/ES.txt > temp && mv temp run/2004/ES.txt



MG - 5016175
ES - 925155
RJ - 4182158
