select estado.id, estado.regiao, estado.name, count(*)
from worker_migrations
join estado on worker_migrations.estado = estado.id
where ano = 2006
group by estado.id, estado.regiao, estado.name;

sed -i "1s/^/MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GRAU INSTR;SEXO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002\n/" run/2004/MG.txt


echo 'MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GRAU INSTR;SEXO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002' | cat - run/2004/MG.txt > temp && mv temp run/2004/MG.txt

echo 'MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GRAU INSTR;SEXO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002' | cat - run/2004/RJ.txt > temp && mv temp run/2004/RJ.txt

echo 'MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GRAU INSTR;SEXO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002' | cat - run/2004/ES.txt > temp && mv temp run/2004/ES.txt



MG - 5016175
ES - 925155
RJ - 4182158


cat nordeste06.TXT | grep "^22" > Piaui.txt && echo 'MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GRAU INSTR;GENERO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002;CLAS CNAE 20;SB CLAS 20;TP DEFIC' | cat - Piaui.txt > temp && mv temp Piaui.txt

echo 'MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GR INSTRUCAO;GENERO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002;CLAS CNAE 20;SB CLAS 20;TP DEFIC;CAUS AFAST 1;DIA INI AF 1;MES INI AF 1;DIA FIM AF 1;MES FIM AF 1;CAUS AFAST 2;DIA INI AF 2;MES INI AF 2;DIA FIM AF 2;MES FIM AF 2;CAUS AFAST 3;DIA INI AF 3;MES INI AF 3;DIA FIM AF 3;MES FIM AF 3;QT DIAS AFAS' | cat - Bahia.txt > temp && mv temp Bahia.txt
echo 'MUNICIPIO;CLAS CNAE 95;EMP EM 31/12;TP VINCULO;CAUSA DESLI;MES DESLIG;IND ALVARA;TIPO ADM;TIPO SAL;OCUPACAO 94;GR INSTRUCAO;GENERO;NACIONALIDAD;RACA_COR;PORT DEFIC;TAMESTAB;NATUR JUR;IND CEI VINC;TIPO ESTBL;IND PAT;IND SIMPLES;DT ADMISSAO;REM MEDIA;REM MED (R$);REM DEZEMBRO;REM DEZ (R$);TEMP EMPR;HORAS CONTR;ULT REM;SAL CONTR;PIS;DT NASCIMENT;NUME CTPS;CPF;CEI VINC;IDENTIFICAD;RADIC CNPJ;TIPO ESTB ID;NOME;DIA DESL;OCUP 2002;CLAS CNAE 20;SB CLAS 20;TP DEFIC;CAUS AFAST 1;DIA INI AF 1;MES INI AF 1;DIA FIM AF 1;MES FIM AF 1;CAUS AFAST 2;DIA INI AF 2;MES INI AF 2;DIA FIM AF 2;MES FIM AF 2;CAUS AFAST 3;DIA INI AF 3;MES INI AF 3;DIA FIM AF 3;MES FIM AF 3;QT DIAS AFAS' | cat - Alagoas.txt > temp && mv temp Alagoas.txt
